### ISSUE TITLE
test that base image provides FGC label

### ISSUE THREAD

**Issue by TomasTomecek** [libre-server/baseruntime-docker-tests#25]
Since base runtime is a docker base image, it should define FGC label, my review comment:

`FGC` is still missing, see [container guidelines](https://fedoraproject.org/wiki/Container:Guidelines#LABELS). I would set it to `f26-boltron`.

**Comment by bgoncalv** [comment]
https://github.com/fedora-modularity/baseruntime-docker-tests/pull/26

**Comment by contyk** [comment]
Implemented in PR#26.
